### ISSUE TITLE
[bug] link <a> is wider than a <div> which it contains

### ISSUE THREAD

**Issue by 5ohdan** [Shramkoweb/Portfolio#322]
On [Dashboard page](https://shramko.dev/dashboard) in Statistics section, links to foreign resources have invisible clickable area on their right.
Probably, the issue is because of [this](https://github.com/Shramkoweb/Portfolio/blob/fd74ead7f9c60c536d2482b13d4c38960d1e3514/components/dashboard-card/dashboard-card.tsx#L11) structure.

---
<img width="673" alt="Screenshot 2024-05-16 at 09 06 53" src="https://github.com/Shramkoweb/Portfolio/assets/23241944/ad80f312-03c5-4a2b-8f53-933b7879d079">
<img width="675" alt="Screenshot 2024-05-16 at 09 06 46" src="https://github.com/Shramkoweb/Portfolio/assets/23241944/86b3cb86-6b67-42ed-ac1b-a5cccae6ca46">

---
*sorry for my english*

**Comment by Shramkoweb** [comment]
@5ohdan Hello. Thanks - I'll put this to work soon 👍

**Comment by Shramkoweb** [comment]
fix/322_link_size

**Comment by Shramkoweb** [comment]
On production. Thnx 🔥
